### ISSUE TITLE
Initial selection does not follow pathSelectionType

### ISSUE THREAD

**Issue by TathagataChakraborti** [reaviz/reagraph#104]
### Describe the bug

The first render with a list of selected nodes, before clicking a button, only highlights the nodes and does not follow the "in" or "out" `pathSelectionType` option to highlight the correct links. 

Coupled with no option to color edges, as brought up in the discussion [here](https://github.com/reaviz/reagraph/discussions/97), there seems to be no way to initialize a partially selected graph correctly.

### Steps to Reproduce the Bug or Issue

Invoke the Canvas element with a non-empty `selections` as input and `pathSelectionType` set to "in" or "out".

### Expected behavior

I was expecting the `pathSelectionType` formatting to be enforced on the initial rendering but only nodes are highlighted.

### Screenshots or Videos

<img width="439" alt="Screenshot 2023-05-18 at 23 24 15" src="https://github.com/reaviz/reagraph/assets/4764242/17ca8c8e-bd7a-4da6-858a-1b8fc576ceed">

### Platform

- Reagraph Version: 4.8.2
- OS: macOS
- Browser: Chrome
- React version: 18.1.0

### Additional context

All I am looking for is more control over the edges really. So if there is a way to format it instead manually instead of using the `useSelection` hook then that will be best.

**Comment by amcdnl** [comment]
Do you see an error in the console? I believe this is because the graph isn't initialized at the time it tries to select thus the issue. https://github.com/reaviz/reagraph/blob/master/src/selection/useSelection.ts#L396

You could probably solve this in a work around by doing a mount effect and setting it there rather than as a initial prop.

**Comment by amcdnl** [comment]
@TathagataChakraborti - Can you retest this? We swapped the graph engine and this should work now.

**Comment by TathagataChakraborti** [comment]
@amcdnl Sorry about the delay. I am on travel atm, but will be back late next week and test. 👍
