### ISSUE TITLE
Node disappears when I move it

### ISSUE THREAD

**Issue by SmirnovArtyom516** [reaviz/reagraph#107]
### Describe the bug

when I take a node and move it to some place, it stays there, however, when I click on the button and set new nodes with connections that include the same node that I moved before, it disappears. And the error "Got NaN while animating: " comes out, as I understand it, this happens because the link to the object is locked inside the react memory, but I try to forcefully delete old links and make a set of new objects, but it still disappears

### Steps to Reproduce the Bug or Issue

make a [ ] of nodes, make the graph draggable, write a func which will change nodes collection and all collection need to have atleast 1 node with the same id, drag one node, and click on button to change [ ] of nodes 

### Expected behavior

atleast i want to re-create the nodes, i dont need that its stay on place where i move it...

### Screenshots or Videos

![image](https://github.com/reaviz/reagraph/assets/100850327/5d6f4be6-d5fa-4dec-9c6e-f67af3c0f4af)

![image](https://github.com/reaviz/reagraph/assets/100850327/8e40de02-7d7a-4e93-a00b-4a84a01e7292)

### Platform

- Reagraph Version: [e.g. 4.8.3]
- OS: [Windows,
- Browser: [Chrome]
- NodeJS version: 16.15

### Additional context

hope u will help, im trying to fix this about 1 week T_T

**Comment by amcdnl** [comment]
@SmirnovArtyom516 - Can you share a reproduction repo? The demos seem to be working fine.

**Comment by SmirnovArtyom516** [comment]
> @SmirnovArtyom516 - Can you share a reproduction repo? The demos seem to be working fine.

i think, i cant give u link on demo couse for demo my project is too big, i will send u a screenshots, if u will need a demo i'll try to transfer on codesand box. 

So, i use a react-redux to save nodes and edges  state in store. And put info from store to graph 

![image](https://github.com/reaviz/reagraph/assets/100850327/0811cf67-8ce7-417a-a8f7-a57736cc0016)

I send a request to api from where new edges are returned to me and I dispatch them to redux

![image](https://github.com/reaviz/reagraph/assets/100850327/3313adbd-cc53-48c8-b2fc-f8bfdfb862e5)

On the sendbox code, I managed to cause this bug, I will now try to find it and throw it here.

Thank you in advance for your help

**Comment by amcdnl** [comment]
Code sandbox would be fine.

**Comment by SmirnovArtyom516** [comment]
> 

Ye, i found, this one

https://codesandbox.io/s/reagraph-example-forked-cfyjfd?file=/src/App.js

**Comment by SmirnovArtyom516** [comment]
> Code sandbox would be fine.

in 4.0.0 version its work correct

**Comment by amcdnl** [comment]
What build system are you using?

**Comment by SmirnovArtyom516** [comment]
@amcdnl 
Hi, thanks for the prompt feedback, the draggable property is very important in my project, I just wanted to clarify if I should wait for a fix for this bug.
If yes, approximately what time?

**Comment by amcdnl** [comment]
@SmirnovArtyom516 - thanks for the demo - I was able to reproduce it. I will have some time on Thursday to check this out and let you know.

**Comment by SmirnovArtyom516** [comment]
@amcdnl 
Hello)
So, may i know  ur verdict?

**Comment by amcdnl** [comment]
should be resolved by https://github.com/reaviz/reagraph/pull/108

**Comment by SmirnovArtyom516** [comment]
@amcdnl 
Thank u so much for this fast fix and fast feedback. 
I really appreciate it :)

**Comment by amcdnl** [comment]
@SmirnovArtyom516 - No problem; it was a tricky one for sure :D. Don't forget to share the word about the project!
