### ISSUE TITLE
Curved Edges

### ISSUE THREAD

**Issue by amcdnl** [reaviz/reagraph#12]
Add the ability to curve the edges/links between the node.

![image](https://user-images.githubusercontent.com/227909/166810192-003d091b-4d87-41b0-9c1a-1178b650be85.png)

Make something like this in `src/utils/position.ts` ( this only kinda works ):

```ts
export const calculateCurve = ({ from, to }) => {
  const midpoint = getMidPoint({ from, to });
  const { distance } = calcDistance({ from, to });

	let multipleVal = Math.pow(midpoint.x, 2);
	multipleVal += Math.pow(midpoint.y, 2);
	multipleVal += Math.pow(midpoint.z, 2);
	multipleVal = Math.pow(distance, 2) / multipleVal;
	multipleVal = multipleVal * 0.1;

	const midX = midpoint.x + multipleVal * midpoint.x;
	const midY = midpoint.y + multipleVal * midpoint.y;
	const midZ = midpoint.z + multipleVal * midpoint.z;

	return [
    new THREE.Vector3(from.x, from.y, from.z),
    new THREE.Vector3(midX, midY, midZ),
    new THREE.Vector3(to.x, to.y, to.z),
  ];
};
```

which could be used like in this component https://github.com/reaviz/reagraph/blob/master/src/symbols/Line.tsx#L14

```tsx
<a.meshLine
  attach="geometry"
  vertices={interpolate(
    [fromVertices, toVertices],
      (a, b) => {
        const [start, mid, end ] = calculateCurve({
          from: { x: a[0], y: a[1], z: a[2] },
          to: { x: b[0], y: b[1], z: b[2] }
        });
        return new THREE.QuadraticBezierCurve3(start, mid, end).getPoints(200);
      }
    )}
/>
```

then you pass a flag on the `GraphCavnas` like `curvedEdges`.

**Comment by evgenoid** [comment]
Do you want to support arrows for curved edges?

**Comment by amcdnl** [comment]
Yes

**Comment by amcdnl** [comment]
This might be helpful: 

- https://hofk.de/main/discourse.threejs/2021/CurvedArrowHelper/CurvedArrowHelper.html
- https://discourse.threejs.org/t/how-to-animate-curved-arrows-in-threejs/36808/11
