### ISSUE TITLE
Overlapping lables in 2-way link via curve arrows

### ISSUE THREAD

**Issue by Arash1381-y** [reaviz/reagraph#137]
### Describe the bug

I expect the label to be above the curved arrow when set the `edgeLabelPosition` to "above" however it won't stop the overlapping labels and the position of labels won't change based on the arrow type (curved or linear)

### Steps to Reproduce the Bug or Issue

run this example
```
const nodes = [{
    id: '1', label: '1'
}, {
    id: '2', label: '2'
}]


const edges = [
    {
        id: '1->2', source: '1', target: '2', label: 'Edge 1-2'

    },
    {
        id: '2->1', source: '2', target: '1', label: 'Something larger'
    }
]

const MyDiagram = () => (
    <GraphCanvas labelType={"all"} edgeInterpolation={"curved"} nodes={nodes} edges={edges} layoutType={"radialOut2d"}
                 draggable theme={darkTheme} edgeLabelPosition={"natural"} />
)

```

### Expected behavior

Set the label above|below of curved arrow based on the configuration.

### Screenshots or Videos

![image](https://github.com/reaviz/reagraph/assets/79264867/67d991c1-7eaf-4008-ba55-d7ec73d0f61c)

### Platform

- Reagraph Version: [e.g. 1.0.0]
- OS:  Linux
- Browser: Firefox
- NodeJS version: 18.14.0

**Comment by amcdnl** [comment]
You should be able to change the label position to be inline and this solve your issue.
