### ISSUE TITLE
z-index of nodes should be higher?

### ISSUE THREAD

**Issue by braco** [reaviz/reagraph#147]
### Describe the bug

The nodes are beneath the edges for some reason. It's unclear how to change this.

### Steps to Reproduce the Bug or Issue

1. create a slightly busy graph

### Expected behavior

Nodes above edges

### Screenshots or Videos

<img width="164" alt="Screenshot 2023-11-11 at 6 50 02 PM" src="https://github.com/reaviz/reagraph/assets/2449172/142a37fb-786e-467d-ad5b-ac5d1c32980e">

### Platform

- Reagraph Version: ^4.14.1
- Browser: Chrome

**Comment by amcdnl** [comment]
You can change the z-index of the spheres. I thought they were the highest, I will recheck though.

**Comment by braco** [comment]
@amcdnl where should the z-index be changed?

**Comment by amcdnl** [comment]
When you hover/select a node, it will now set that node to top.
