### ISSUE TITLE
cameraMode="pan" doesn't work on mobile

### ISSUE THREAD

**Issue by umuttalha** [reaviz/reagraph#154]
### Describe the bug

I wanna navigate the map make pan camera mode but not works on mobile

### Steps to Reproduce the Bug or Issue

I wanna navigate the map make pan camera mode but not works on mobile

### Expected behavior

as a use i expected not rotate on mobile when i set cameraMode="pan"

### Platform

- Reagraph Version: [e.g. 1.0.0]
- OS:  macOS
- Browser: Chrome, Edge
- NodeJS version:20.10

**Comment by nadavq** [comment]
Any update on this?

**Comment by nadavq** [comment]
@amcdnl

**Comment by Edouard-Tby** [comment]
Also interested in the fix. Thank you !

**Comment by nadavq** [comment]
Hi, any update on this please?

**Comment by mcm97** [comment]
Also interested in a fix or any pointers how to mitigate it :)
