### ISSUE TITLE
Clustering: templateForce is undefined

### ISSUE THREAD

**Issue by greyhillman** [reaviz/reagraph#155]
### Describe the bug

When rendering a graph that has clustering enabled via `clusterAttribute`, a runtime error occurs with "TypeError: templateForce is undefined".

~~This just started happening in 4.15.0, which I just happened to use just as it was released. When I go back to 4.14.2, the graph works fine.~~
Edit: Was able to get the same error on the previous version.

### Steps to Reproduce the Bug or Issue

1. Create a simple graph with lots of nodes.
2. Add `data: { cluster: "test" }` to each node.
3. Set `clusterAttribute="cluster"` on `GraphCanvas`
4. Reload the page a few times.

### Expected behavior

The graph will render with all nodes in a single cluster.

### Platform

- Reagraph Version: 4.14.2, 4.15.0
- OS: Linux
- Browser: Firefox
- NodeJS version: ...

### Additional context

```typescript
let nodes: GraphNode[] = [
    {
        id: '1',
        data: {
            cluster: "test"
        }
    },
    ...
];
const edges: GraphEdge[] = [];

return (
    <GraphCanvas nodes={nodes} edges={edges} clusterAttribute="cluster" />
);
```

**Comment by amcdnl** [comment]
I can't seem to reproduce this - can you give us a demo repo?

**Comment by greyhillman** [comment]
I'll try and get that repo for ya on the weekend. I was also trying to
figure out how to reproduce it reliably and whether the issue was a recent
version or not.

**Comment by greyhillman** [comment]
Got a repo for ya: https://github.com/greyhillman/reagraph-test

When running `npm run dev`, the error appears on each page refresh (and a few times in the console). In "src/App.tsx", if you remove the `clusterAttribute="cluster"` line, the graph will load fine, even after refreshing. What's definitely strange though is if you add back in the `clusterAttribute="cluster"` line while in `npm run dev` and without refreshing, the graph will appear with clusters and no errors. But, on refresh, the page errors like before.

**Comment by amcdnl** [comment]
I was able to reproduce your issue. It seems like there are a couple of issues. 

1. The nodes + edges IDs don't match up
2. You are initilizing the graph with no nodes or edges - you need to conditionally show graph when its loaded
