### ISSUE TITLE
Clustering not working

### ISSUE THREAD

**Issue by thobhanifreddy** [reaviz/reagraph#162]
### Describe the bug

After the last commit cluster seems to be broken 

Looks like this happened because of error thrown here https://reagraph.dev/?path=/story/demos-cluster--simple

### Steps to Reproduce the Bug or Issue

Checkout storybook: https://reagraph.dev/?path=/story/demos-cluster--simple

### Expected behavior

Clustering should work

### Platform

- Reagraph Version: 4.15.3
- OS: All
- Browser: All
- NodeJS version: 18.X.X

### Your Example Website or App

https://reagraph.dev/?path=/story/demos-cluster--simple

**Comment by amcdnl** [comment]
This is fixed now.
