### ISSUE TITLE
Save As Image

### ISSUE THREAD

**Issue by amcdnl** [reaviz/reagraph#17]
Add helpers for saving a graph as an image.

https://stackoverflow.com/questions/15558418/how-do-you-save-an-image-from-a-three-js-canvas

**Comment by amcdnl** [comment]
This is going to have some performance impacts so I think we should hold off on this for now until we understand the need more. 

A potential other solution might be: https://www.npmjs.com/package/@react-three/test-renderer but its experimental and not sure how well it would handle more advanced stuff.

**Comment by MortezaNajafian** [comment]
is there any way to save graph as image? or download it?

**Comment by MortezaNajafian** [comment]
Please add this feature Everything is ok, but I need this feature for downloading images of the chart.
