### ISSUE TITLE
Lasso selection is not working

### ISSUE THREAD

**Issue by thobhanifreddy** [reaviz/reagraph#177]
### Describe the bug

I can no longer select nodes and edges on the Lesso example in the storybook. https://reagraph.dev/?path=/story/demos-selection-lasso--dragging

### Steps to Reproduce the Bug or Issue

1. go to https://reagraph.dev/?path=/story/demos-selection-lasso--dragging
2. Hold shift and try selecting 

### Expected behavior

Should able to select nodes and edges

### Platform

- Reagraph Version: 4.15.8
- OS: all
- Browser: chrome

**Comment by amcdnl** [comment]
Fixed in latest - sorry about that - inverted logic on the nextjs fix
