### ISSUE TITLE
Lasso won't select nodes if custom nodes are used

### ISSUE THREAD

**Issue by royassis** [reaviz/reagraph#211]
### Describe the bug

Lasso won't select nodes if custom nodes are used:
https://reagraph.dev/?path=/docs/docs-advanced-custom-nodes--docs

### Steps to Reproduce the Bug or Issue

See https://reagraph.dev/?path=/docs/docs-advanced-custom-nodes--docs and add `lassoType={"node"}`

### Expected behavior

Lasso selected nodes

### Platform

- Reagraph Version: 4.15.24
- OS: Windows
- Browser: Chrome
- NodeJS version: v18.17.1

**Comment by amcdnl** [comment]
Ah - you have to set the `userData` - https://github.com/reaviz/reagraph/blob/master/src/symbols/Node.tsx#L383

Would you mind making a PR for docs for this?
