### ISSUE TITLE
How can I use Chinese text as label?

### ISSUE THREAD

**Issue by xxleyi** [reaviz/reagraph#23]
I am from China, is trying this awesome libary to test some idea, but meet a problem: seems it can not render Chinese text as label.

**Comment by amcdnl** [comment]
I would love to support Chinese - would you mind providing an example of the broken feature in Chinese so I can examine it?

**Comment by xxleyi** [comment]
> I would love to support Chinese - would you mind providing an example of the broken feature in Chinese so I can examine it?

I diged into font rendering with canvas, and I found `reagraph` use `@react-three/drei` do `text rendering`, and user need paas a font url to it, not font family. So I think `reagraph` may should expose an api to let users can paas a font url.

Demo: https://codesandbox.io/s/text-in-three-forked-nhv234?file=/src/index.js

**Comment by amcdnl** [comment]
@xxleyi - Sorry for delayed response. I'm happy to accept a PR to allow passing this if you like.

**Comment by amcdnl** [comment]
Merged! Thanks for the contribution! I will cuz a release Monday w/ some more updates too!
