### ISSUE TITLE
nodeSeparation not working as expected

### ISSUE THREAD

**Issue by manjunathgk22** [reaviz/reagraph#262]
### Describe the bug

nodeSeparation is not applied to all the nodes. 

### Steps to Reproduce the Bug or Issue

1. Create a graph with layoutType="hierarchicalLr"
2. apply nodeSeparation: 1.3, 
3. Change is reflected only on leaf nodes

### Expected behavior

nodeSeparation should be applied uniformly across all the nodes

### Screenshots or Videos

<img width="292" alt="Screenshot 2024-08-05 at 11 23 29 PM" src="https://github.com/user-attachments/assets/b3520ff2-c104-41d0-9e8b-dde09ed3ba6e">
<img width="336" alt="Screenshot 2024-08-05 at 11 23 36 PM" src="https://github.com/user-attachments/assets/61f585d8-1bbc-46b0-acda-c2eb69370879">

In these screenshots one has nodeSeparation as `1` and the other `1.2`  distance between first 2 nodes is same in both.

### Platform

- Reagraph Version: 4.19.2
- OS: macOS
- Browser: Chrome
- NodeJS version: v19.9.0

**Comment by ghsteff** [comment]
Hmmm played around with the tree in [this playground](https://observablehq.com/@d3/d3-hierarchy) for d3.hierarchy (the library we use for the graph layout) and this behavior looks expected

[Here's](https://observablehq.com/@d3/d3-hierarchy) the docs for the `seperation` function 

This paragraph probably has the answer

> The separation accessor is used to separate neighboring nodes. The separation function is passed two nodes a and b, and must return the desired separation. The nodes are typically siblings, though the nodes may be more distantly related if the layout decides to place such nodes adjacent.

Maybe "neighboring nodes" means neighboring leafs? And the separation you're talking about is between parent and child, not siblings

Here's separation of `1` and `1.3` for reference. The behavior looks identical to you're screenshots

![Untitled2](https://github.com/user-attachments/assets/bf1b3463-a6ee-4c09-8b9e-9aaaa7b4be35)
![Untitled](https://github.com/user-attachments/assets/bacde094-d31b-404d-80e6-c7341ed70830)

**Comment by ghsteff** [comment]
Maybe try playing with the `nodeSize` layout override. It won't actually change the rendered nodes size, but it will cause more space between nodes in every direction in the d3-hierarchy algo

https://reagraph.dev/?path=/docs/docs-getting-started-layouts--docs#hierarchical-2d
