### ISSUE TITLE
labelType "none" still shows label when hovering over node

### ISSUE THREAD

**Issue by Obaydahm** [reaviz/reagraph#264]
### Describe the bug

When hovering over a node the label becomes visible even though labelType is set to none.

The default label is the one that is not rendering correctly because it is of special characters. 
I want to disable the default label completely and handle it myself.

### Steps to Reproduce the Bug or Issue

1. Set `labelType` to `none`
2. Hover over a node

### Expected behavior

As a user, when I set `labelType` to `none`, and I hover `node`, I expect the default label to NOT be shown.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/5faf79be-2837-4aa6-b20d-c7103bb6d9b2)

### Platform

- Reagraph Version: 4.19.2
- OS: Mac
- Browser: Edge
- NodeJS version: 16.20.0

**Comment by dtsuper3** [comment]
https://github.com/reaviz/reagraph/pull/265

https://github.com/user-attachments/assets/eb7157d2-21dc-4f1e-a8ab-0138fa842eb6
