### ISSUE TITLE
Line Arrow Position Issue

### ISSUE THREAD

**Issue by amcdnl** [reaviz/reagraph#29]
Lines should stop at the end of the arrow.

![image](https://user-images.githubusercontent.com/227909/174814132-158e5c48-8fa2-467c-9f79-c7fe2772996b.png)

**Comment by evgenoid** [comment]
Now I see a little bit different problem - arrow has wrong scale
<img width="372" alt="Screenshot 2022-06-27 at 09 04 14" src="https://user-images.githubusercontent.com/1290843/175870440-66989eb0-8076-4e56-a9d8-8740abfec541.png">
<img width="401" alt="Screenshot 2022-06-27 at 09 04 24" src="https://user-images.githubusercontent.com/1290843/175870442-907c5374-e212-40dd-b24b-d44adf2a94a3.png">
