### ISSUE TITLE
Edge Label Backgrounds

### ISSUE THREAD

**Issue by amcdnl** [reaviz/reagraph#35]
We probably need to add a background ( optionally ) via the theme for edge labels so you can read them easier: 

![image](https://user-images.githubusercontent.com/227909/175577121-a387ae76-a002-435b-80fc-bdeffe561acc.png)

like they did here:

![image](https://user-images.githubusercontent.com/227909/175577213-f5d9c984-4859-483b-8021-3aacae207a79.png)

**Comment by evgenoid** [comment]
The main problem is that we can't add some background to the text, just `outline` with some width and background color.
If we look in detail at the example - it uses the same approach.
In our case it looks next (outlineWidth=2):
<img width="363" alt="Screenshot 2022-06-25 at 18 43 45" src="https://user-images.githubusercontent.com/1290843/175781165-be9abcbc-2043-4aaf-9cae-025b7cfcec29.png">

**Comment by amcdnl** [comment]
Let's make this optional w/ via theme `stroke` option. Let's also make a SB for this example too.

**Comment by amcdnl** [comment]
This is somewhat blocked by https://github.com/protectwise/troika/discussions/213
