### ISSUE TITLE
Hovering Labels w/ Ellipsis

### ISSUE THREAD

**Issue by amcdnl** [reaviz/reagraph#36]
When you hover a label that has a ellipsis we might want to think about if we want expand all the text.

![image](https://user-images.githubusercontent.com/227909/175583576-a52c8fc9-d235-49b0-80e3-df90a828d401.png)

**Comment by neil-morrison44** [comment]
Would be nice to expose some control over the ellipsis, if there isn’t any yet - most of the graphs I’m generating could fit probably twice as much text as what’s shown.

Multi-line / `break-word` style options on the labels would be really nice.

**Comment by amcdnl** [comment]
@neil-morrison44 - 

> Would be nice to expose some control over the ellipsis

Ya - i think thats what I'm going to do for the short term.

> Multi-line / break-word style options on the labels would be really nice.

Happy to accept a PR if you want to take a stab at it. Its pretty tricky to do in WebGL though.

**Comment by amcdnl** [comment]
This is an interesting approach...

<img width="375" alt="image" src="https://user-images.githubusercontent.com/227909/175977556-396ce54e-b2db-4a31-bc49-925324b64b08.png">

https://sim51.github.io/react-sigma/
