### ISSUE TITLE
Icons inside Spheres

### ISSUE THREAD

**Issue by amcdnl** [reaviz/reagraph#41]
Add the ability to have an icon inside a sphere like this:

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/227909/176229660-7bee09cc-c6e3-4c21-bc18-9c423deba66a.png">

I realize that is 2d and this is a 3d canvas but worth a shot.

**Comment by J-Ajah** [comment]
@amcdnl  I love the work and effort put into the creation of this library as it is neat and flexible compared to other libraries I have tried out on the internet.

This use case suits my current implementation target and I would like to recommend that an option for labels to be added inside the sphere be made possible as well. So the user has the flexibility of showing the node's label inside the sphere or outside as already implemented.

Great work once again!

![Screenshot (3)](https://user-images.githubusercontent.com/77506031/181935702-90945d57-b9dc-432c-b277-5b42c75f9302.png)

**Comment by amcdnl** [comment]
@J-Ajah - Label positions (inside nodes / etc ) is not currently on the roadmap. Would you log a ticket for that so we can track it separately? 

This item is not closed so you could technically achieve it with this but its going to be a little messy. I think labels inside nodes is going to be a limited use case due to the size of the node and the length of most words.
