### ISSUE TITLE
Dragging Offset Bug

### ISSUE THREAD

**Issue by amcdnl** [reaviz/reagraph#42]
When there is a offset ( such as margin ) when you drag, the cursor offset is wrong. 

It needs to take into account canvas dom element offset in the page like I did here: https://github.com/reaviz/reaflow/blob/master/src/utils/helpers.ts#L51-L58

You can reproduce it in this minimal example which uses the same logic: https://codesandbox.io/s/react-three-draggable-gesture-offset-bug-oumtsn?file=/src/App.js

Code: https://github.com/reaviz/reagraph/blob/master/src/utils/useDrag.ts#L47

**Comment by evgenoid** [comment]
Actually don't understand what's wrong.
I see that when I start to drag - the cube element shifted on mouse down action
https://user-images.githubusercontent.com/1290843/176422036-bb35ed55-3739-47dd-9d14-06d71727b3dd.mov

How is it related to our system?

**Comment by Edouard-Tby** [comment]
@amcdnl I still have an offset with the latest version of the library. Any any why? Thanks a lot !

https://github.com/user-attachments/assets/d3de32cb-823b-4cd8-8245-71d93f0311e3
