### ISSUE TITLE
Path Finding not working as expected

### ISSUE THREAD

**Issue by amcdnl** [reaviz/reagraph#48]
The path finding is not highlighting like one would expect.

Currently it looks like:

![image](https://user-images.githubusercontent.com/227909/178480764-8ffbed60-749d-413a-83e1-0f2c069cfa07.png)

It should be like:

![image](https://user-images.githubusercontent.com/227909/178480938-651e1719-a467-46e9-8eb1-6d608f5e67ef.png)

So it would be defined as:

- Node 1 and Node 9 should be highlighted w/ rings
- Node 2 and Node 4 should be highlighted
- Only edges in the path should be highlighted ( Example Node 2 > Node 5 would not be highlighted )

**Comment by manjunathgk22** [comment]
@amcdnl  How do I highlight **only** the nodes that are in the path?
