### ISSUE TITLE
Concerning undelying graph data structure / model API : `ngraph` vs `graphology`

### ISSUE THREAD

**Issue by cliffordfajardo** [reaviz/reagraph#61]
## ngraph vs graphology
Not urgent, just  wanted to share `graphology`  and get your thoughts on it compared to `ngraph` for reagraph's underlying graph data structure 😄  

## `grapology` highlights
Compared to `ngraph`,`graphology` supports a more rich out of the box API for the graph:
- comprehensive standard library of algorithms, graph generators, layouts traversals , event listeners & utility functions
![CleanShot 2022-08-07 at 07 59 53@2x](https://user-images.githubusercontent.com/6743796/183297288-2ab16561-1c10-48d9-80f5-e8aedc4259a8.png)
- layout algorithms offer sync and async versions (using web workers)
The library is used by other more recent graph libraries like [sigmajs](https://www.sigmajs.org/) and [pixi-graph](https://github.com/zakjan/pixi-graph) for the graph backend.

Besides the rich API, another strong aspect for the library is that its a community driven effort to help graph libraries share layouts, algorithms etc. In practice this means someone using `sigmajs` for example could move to `pixi-graph`or even `reagraph` (if it used graphology) since they share the same underlying graph structure
 [Jan Zak](https://github.com/zakjan), talks about graphology in this YouTube video [here](https://youtu.be/pe2PgFVvtLs?t=459)

**Centralized documentation**
- Ngraph's packages are all scattered across different individual repos. Whereas's graphology has everything in one mono-repo
- For those wanting to customize reagraph, the centralized documentation with `graphology` is a big DX & productivity win

**Comment by amcdnl** [comment]
Thanks for sharing this - never seen graphology before. I'm open to exploring it. Would you be interested in taking a first stab at it?

**Comment by cliffordfajardo** [comment]
> Thanks for sharing this - never seen graphology before. I'm open to exploring it. Would you be interested in taking a first stab at it?

I'm interested - busy at work & life transitions, but can't really give an ETA 😅 
Created the issue mostly so I don't forget to revisit / get feedback for now

**Comment by amcdnl** [comment]
I dug into this and I'm on board. Still open to helping w/ it ?

**Comment by cliffordfajardo** [comment]
Haven't forgot about the github ^^ comment 😄
Been super busy these days but its definetely something I want to explore! I'll get back to you later in the week
