### ISSUE TITLE
Enable Github Discussions Tab

### ISSUE THREAD

**Issue by cliffordfajardo** [reaviz/reagraph#63]
What do you think about enabling the  Github Discussions tab for this repo 
People can ask questions, get help, share solutions here (hopefully) 😄 

Example Discussions tab for `react-query` repo:
- https://github.com/TanStack/query/discussions

![CleanShot 2022-08-07 at 11 15 19@2x](https://user-images.githubusercontent.com/6743796/183305179-648f2bd7-9a13-4727-973e-ffeb7b5c60f6.png)

**Comment by amcdnl** [comment]
Done!
