### ISSUE TITLE
Context Menu being rendered outside of global App context

### ISSUE THREAD

**Issue by czescwojtek** [reaviz/reagraph#70]
### Describe the bug

Hi there! 
A React component passed as the `contextMenu` prop is being rendered, when triggered, outside the global App tree. Making it appear as another root of the app and not being able to reach any of the parent contexts/context providers. I believe it's a major limitation, making it impossible for the context menu to be a full-fledged React component.

### Steps to Reproduce the Bug or Issue

1. Go to the sandbox link.
2. Follow the 'go to example' link.
3. Try to open up the context menu of a node
4. Experience an error

(Switch from ContextMenu to ContextMenu_safe to see the working menu)

### Expected behavior

As a user, I would expect the Context Menu component not to fall outside the global App tree/flow, thus being unable to consume any of the context providers.

### Screenshots or Videos

<img width="220" alt="image" src="https://user-images.githubusercontent.com/3768638/187065896-54b9f136-451c-4577-9cb4-15323c3a153d.png">

### Platform

- Reagraph Version: 4.1.0
- OS: macOS latest
- Browser: Chrome latest

### Your Example Website or App

https://codesandbox.io/s/damp-smoke-dnn8d6?file=/src/index.graph.tsx

**Comment by amcdnl** [comment]
The context menu uses `import { Html } from '@react-three/drei';`. I'm not doing anything outside of that so I'd recommend we log this on the drei repo.
