### ISSUE TITLE
Not able to display Node name characters in other languages?

### ISSUE THREAD

**Issue by sunneydev** [reaviz/reagraph#71]
### Describe the bug

Is Reagraph not able to display characters in other languages? I'm not really sure how the canvas renders text, but if it's UTF-8 it should've worked on the Georgian language, but puts boxes instead.

### Steps to Reproduce the Bug or Issue

1. Name any node "ტესტი"
2. It will show up as boxes

### Expected behavior

It should display the Georgian characters, puts boxes instead. 

### Screenshots or Videos

<img width="79" alt="image" src="https://user-images.githubusercontent.com/55714870/187391455-b04b9b15-1a2f-46a5-86bc-11be6bbc9e08.png">

### Platform

- Reagraph Version: [e.g. 1.0.0]
- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- NodeJS version: ...

**Comment by amcdnl** [comment]
You need to use this: https://github.com/reaviz/reagraph/pull/37 in order to use custom languages.

**Comment by amcdnl** [comment]
We should add this to the docs - Would u mind making a PR to add it under FAQ?

**Comment by sunneydev** [comment]
@amcdnl I'm not sure where FAQ is, I could possibly add it as a story as well under `demos/labels`

**Comment by amcdnl** [comment]
Sorry - should have been more clear - we need a new FAQ page :D
