### ISSUE TITLE
Support for Japanese / non-Latin characters

### ISSUE THREAD

**Issue by constantin-barbu** [reaviz/reagraph#91]
### Describe the bug

I'm trying to make a graph with Japanese labels (written in kanji or katakana) and it seems to be unsupported by the library. Is there a way to change the default font or can support be added for such a feature?

### Steps to Reproduce the Bug or Issue

Load any dataset with labels in Japanese.

### Expected behavior

Labels should be displayed.

### Screenshots or Videos

![Screenshot 2022-10-28 at 21 33 41](https://user-images.githubusercontent.com/38275345/198718218-050e792f-4d52-4311-b3a0-5ca4313efdb5.png)

### Platform

- Reagraph Version: 4.7.0
- OS: macOS 13
- Browser: Chrome, Safari

**Comment by amcdnl** [comment]
This is supported - https://reagraph.dev/?path=/story/docs-getting-started-faq--page
