### ISSUE TITLE
Edge labels not visible in nextjs production build

### ISSUE THREAD

**Issue by kanitsharma** [reaviz/reagraph#93]
### Describe the bug

Edge labels not visible in nextjs production build.

<img width="326" alt="Screenshot 2022-11-03 at 3 49 30 PM" src="https://user-images.githubusercontent.com/23506120/199696445-65b59d5a-64e5-469d-bb4c-51345de04979.png">

No errors in console.

It is present in component tree, checked in react devtools.

<img width="665" alt="Screenshot 2022-11-03 at 3 51 20 PM" src="https://user-images.githubusercontent.com/23506120/199696791-eacdf462-6b04-4824-bb22-7d8e6b89e07d.png">

Working properly in development server.

<img width="288" alt="Screenshot 2022-11-03 at 3 52 27 PM" src="https://user-images.githubusercontent.com/23506120/199697010-1a3cbc2e-4593-4c16-8dce-ed7d98f56acf.png">

Tested on chrome and firefox with reagraph@4.7.0

### Steps to Reproduce the Bug or Issue

1. `yarn create next-app reagraph-edgelabel-issue`
2. `yarn add reagraph`
3. Usage
```javascript
import dynamic from "next/dynamic";

const GraphCanvas = dynamic(
  import("reagraph").then((mod) => mod.GraphCanvas),
  { ssr: false }
);

export default function Test() {
  return (
    <GraphCanvas
      labelType="all"
      nodes={[
        {
          id: "n-1",
          label: "1",
        },
        {
          id: "n-2",
          label: "2",
        },
      ]}
      edges={[
        {
          id: "1->2",
          source: "n-1",
          target: "n-2",
          label: "Edge 1-2",
        },
      ]}
    />
  );
}

```
4. `yarn build` and `yarn start`

### Expected behavior

Edge labels should be visible.

### Platform

- Reagraph Version: 4.7.0
- OS: macOS
- Browser: Chrome, Firefox
- NodeJS version: 16.17.1

**Comment by infosechoudini** [comment]
same

**Comment by amcdnl** [comment]
@infosechoudini / @kanitsharma - Any chance you could make me an example repo? I'm not super familiar with Next.

**Comment by kanitsharma** [comment]
@amcdnl @infosechoudini  It seems to be fixed in reagraph v4.11.1 and next v13.4.12. Its been a while but If I remember correctly this issue was specific to v4.7.0. In my case I reverted back to v4.5.0 and it was working fine, if that helps.

**Comment by hechtjo** [comment]
I observe this issue in a project built with Vite 4.4, React 18 and Reagraph 4.14.1, Setting reagraph to older versions has no effect.  Does anyone know what might be the cause for this? I see that a newly created nextjs 14 project does work fine

**Comment by amcdnl** [comment]
NextJS should now not error.

**Comment by wasimsandhu** [comment]
Unfortunately I'm not seeing edge labels in my Next.js app. I'm using reagraph ^4.21.0 and next.js 14.2.16. If I use `labelType="all"` or `labelType="auto"`, then all of the edge labels appear in the center of the graph.
