### ISSUE TITLE
'RenderNode' cause 'onNodeClick' to stop working

### ISSUE THREAD

**Issue by danielyogel** [reaviz/reagraph#99]
### Describe the bug

When rendering a custom node using 'renderNode' - clicking on a node does not tigger the related function provided using 'onNodeClick'.

### Steps to Reproduce the Bug or Issue

1. add a custom renderer using 'RenderNode' 2
2. add a click handler using 'onNodeClick'
3. click on one of the nodes.

### Expected behavior

function from onNodeClick should fire.

### Platform

  "reagraph": "^4.7.0",

MacOS Chrome

**Comment by amcdnl** [comment]
Can you provide an example?

**Comment by amcdnl** [comment]
If you can provide some code, maybe i can help. closing until then.
